services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
      - BASE_API_URL=http://backend:3030/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
    env_file:
      - ./backend/.env
    volumes:
      - backend-db:/app/prisma
    restart: unless-stopped

volumes:
  backend-db: